### ISSUE TITLE
Add Xor-editor

### ISSUE THREAD

**Issue by Narulacodes** [ktrvs/listy#2]
Add Xor-editor by @nanomotion https://github.com/xor-editor/xor
Support for js,css and htl.

**Comment by vutondesign** [comment]
Okay, Would you like to take this?

**Comment by Narulacodes** [comment]
Sure

**Comment by Nanomotion** [comment]
Thanks for recommending it. I moved it back to https://github.com/Nanomotion/xor, and I can add a PR if you'd like.

**Comment by Narulacodes** [comment]
I made A PR.
I fix it.
Thanks!
